In [1]:
%load_ext autoreload
%autoreload 2

import sys
import os
import time

import matplotlib.pyplot as plt
%matplotlib inline
from multiprocess import Pool
import numpy as np

sys.path.append(os.environ['REPO_DIR'] + '/utilities')
from utilities2015 import *
from metadata import *
from data_manager import *

from registration_utilities import *

/home/yuncong/MouseBrainAtlas/src/utilities/utilities2015.py:2: UserWarning: 
This call to matplotlib.use() has no effect because the backend has already
been chosen; matplotlib.use() must be called *before* pylab, matplotlib.pyplot,
or matplotlib.backends is imported for the first time.

The backend was *originally* set to 'module://ipykernel.pylab.backend_inline' by the following code:
  File "/usr/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/home/yuncong/MouseBrainAtlas/mousebrainatlas_virtualenv/lib/python2.7/site-packages/ipykernel_launcher.py", line 16, in <module>
    app.launch_new_instance()
  File "/home/yuncong/MouseBrainAtlas/mousebrainatlas_virtualenv/local/lib/python2.7/site-packages/traitlets/config/application.py", line 658, in launch_instance
    app.start()
  File "/home/yuncong/MouseBrainAtlas/mousebrainatlas_virtuale

Setting environment for Precision WorkStation
{'MD585': 0.46, 'UCSD001': 0.3125}


No vtk
Seems you are using operation INIs to provide cropbox.
Seems you are using operation INIs to provide cropbox.
No anchor.txt is found. Seems we are using the operation ini to provide anchor. Try to load operation ini.
Failed to cache MD594 anchor: ini file /media/yuncong/BstemAtlasData/atlas_data/CSHL_data_processed/MD594/operation_configs/from_none_to_aligned.ini does not exist.
File does not exist: /media/yuncong/BstemAtlasData/atlas_data/CSHL_data_processed/MD594/MD594_sorted_filenames.txt
Failed to cache MD594 sections_to_filenames: 
File does not exist: /media/yuncong/BstemAtlasData/atlas_data/CSHL_data_processed/MD594/MD594_sorted_filenames.txt
Failed to cache MD594 filenames_to_sections: 
No anchor.txt is found. Seems we are using the operation ini to provide anchor. Try to load operation ini.
Failed to cache MD594 section_limits: ini file /media/yuncong/BstemAtlasData/atlas_data/CSHL_data_processed/MD594/MD594_prep2_sectionLimits.ini does not exist.
No anchor.txt is found

In [2]:
# For DEMO998, use atlasV7
atlas_spec = dict(name='atlasV7',
                   vol_type='score'    ,               
                    resolution='10.0um'
                   )

# atlas_spec = dict(name='atlasV6',
#                    vol_type='score'    ,               
#                     resolution='10.0um'
#                    )

In [3]:
atlas_structures_wrt_canonicalAtlasSpace_atlasResol = \
DataManager.load_original_volume_all_known_structures_v3(atlas_spec, in_bbox_wrt='canonicalAtlasSpace',
                                                        out_bbox_wrt='canonicalAtlasSpace')

Prior structure/index map not found. Generating a new one.


In [4]:
atlas_structure_centroids_wrt_canonicalAtlasSpace_atlasResol = get_structure_centroids(vol_origin_dict=atlas_structures_wrt_canonicalAtlasSpace_atlasResol)

In [5]:
atlas_anchor1_wrt_canonicalAtlasSpace_atlasResol = \
np.r_[atlas_structure_centroids_wrt_canonicalAtlasSpace_atlasResol['12N'][:2], 0]
atlas_anchor2_wrt_canonicalAtlasSpace_atlasResol = \
np.r_[atlas_structure_centroids_wrt_canonicalAtlasSpace_atlasResol['3N_R'][:2], 0]

In [6]:
# stack = 'CHATM2'
# stack = 'MD661'
# stack = 'DEMO998'
stack = 'MD585'

In [7]:
intensity_volume_spec = dict(name=stack, resolution='10.0um', prep_id='wholebrainWithMargin', vol_type='intensity')

_, wholebrainWithMargin_origin_wrt_wholebrain_dataResol = \
DataManager.load_original_volume_v2(intensity_volume_spec, return_origin_instead_of_bbox=True)

wholebrainWithMargin_origin_wrt_wholebrain_dataResol_x, \
    wholebrainWithMargin_origin_wrt_wholebrain_dataResol_y, \
    wholebrainWithMargin_origin_wrt_wholebrain_dataResol_z = \
wholebrainWithMargin_origin_wrt_wholebrain_dataResol

In [8]:
# Test 20181203

if stack == 'MD585':
    mid_z_wrt_wholebrainWithMargin = 120.
    subject_anchor1_wrt_wholebrain_atlasResol = np.array([wholebrainWithMargin_origin_wrt_wholebrain_dataResol_x * 10. + 613*20., 
                                                          wholebrainWithMargin_origin_wrt_wholebrain_dataResol_y * 10. + 226*20., 
                                                          wholebrainWithMargin_origin_wrt_wholebrain_dataResol_z*10. + mid_z_wrt_wholebrainWithMargin*20.]) / 10.
    subject_anchor2_wrt_wholebrain_atlasResol = np.array([wholebrainWithMargin_origin_wrt_wholebrain_dataResol_x * 10. + 451*20., 
                                                          wholebrainWithMargin_origin_wrt_wholebrain_dataResol_y * 10. + 161*20., 
                                                          wholebrainWithMargin_origin_wrt_wholebrain_dataResol_z*10. + mid_z_wrt_wholebrainWithMargin*20.]) / 10.

In [8]:
# # Pick the x/y coordinates on the intensity volume (no margin).
# # Use the thumbnail sagittal panel (right bottom) in brain_labeling_gui. 
# # Click a point while holding down space bar, then you can read off the coordinates at the GUI window's title bar.

# # bug? Must click on lossless to get accurate coordinates.

# # It seems subject_anchor2_wrt_wholebrainWithMargin_atlasResol are misnomer.
# # they should really be subject_anchor1_wrt_wholebrain_atlasResol.

# if stack == 'CHATM2':
#     subject_anchor1_wrt_wholebrainWithMargin_atlasResol = np.array([565,246,179]) * 20. / 10. # 12N
#     subject_anchor2_wrt_wholebrainWithMargin_atlasResol = np.array([388,183,179]) * 20. / 10. # 3N_L
# elif stack == 'CHATM3':
#     subject_anchor1_wrt_wholebrainWithMargin_atlasResol = np.array([740,258,230]) * 20. / 10.
#     subject_anchor2_wrt_wholebrainWithMargin_atlasResol = np.array([550,195,230]) * 20. / 10.
# elif stack == 'MD593':
#     subject_anchor1_wrt_wholebrainWithMargin_atlasResol = np.array([647*20., 233*20., 164*10.+138*20.]) / 10.
#     subject_anchor2_wrt_wholebrainWithMargin_atlasResol = np.array([474*20., 171*20., 164*10.+138*20.]) / 10.
# elif stack == 'MD589':
#     # Here 605 is the x of 12N's center, 260 is the y of 12N's center, 135 is the z of mid-sagittal plane. All in GUI's intensity volume voxel unit (20um/voxel).
#     subject_anchor1_wrt_wholebrainWithMargin_atlasResol = np.array([605*20., 260*20., wholebrainWithMargin_origin_wrt_wholebrain_dataResol_z*10.+135*20.]) / 10.
#     subject_anchor2_wrt_wholebrainWithMargin_atlasResol = np.array([456*20., 175*20., wholebrainWithMargin_origin_wrt_wholebrain_dataResol_z*10.+135*20.]) / 10.
# elif stack == 'MD585':
#     subject_anchor1_wrt_wholebrainWithMargin_atlasResol = np.array([614*20., 241*20., wholebrainWithMargin_origin_wrt_wholebrain_dataResol_z*10.+117*20.]) / 10.
#     subject_anchor2_wrt_wholebrainWithMargin_atlasResol = np.array([423*20., 165*20., wholebrainWithMargin_origin_wrt_wholebrain_dataResol_z*10.+145*20.]) / 10.
# elif stack == 'MD590':
#     subject_anchor1_wrt_wholebrainWithMargin_atlasResol = np.array([650*20., 239*20., wholebrainWithMargin_origin_wrt_wholebrain_dataResol_z*10.+124*20.]) / 10.
#     subject_anchor2_wrt_wholebrainWithMargin_atlasResol = np.array([473*20., 159*20., wholebrainWithMargin_origin_wrt_wholebrain_dataResol_z*10.+124*20.]) / 10.
# elif stack == 'MD591':
#     subject_anchor1_wrt_wholebrainWithMargin_atlasResol = np.array([637*20., 287*20., wholebrainWithMargin_origin_wrt_wholebrain_dataResol_z*10.+124*20.]) / 10.
#     subject_anchor2_wrt_wholebrainWithMargin_atlasResol = np.array([469*20., 190*20., wholebrainWithMargin_origin_wrt_wholebrain_dataResol_z*10.+124*20.]) / 10.
# elif stack == 'MD592':
#     subject_anchor1_wrt_wholebrainWithMargin_atlasResol = np.array([647*20., 223*20., wholebrainWithMargin_origin_wrt_wholebrain_dataResol_z*10.+136*20.]) / 10.
#     subject_anchor2_wrt_wholebrainWithMargin_atlasResol = np.array([470*20., 180*20., wholebrainWithMargin_origin_wrt_wholebrain_dataResol_z*10.+136*20.]) / 10.
# elif stack == 'MD594':
#     subject_anchor1_wrt_wholebrainWithMargin_atlasResol = np.array([650*20., 189*20., wholebrainWithMargin_origin_wrt_wholebrain_dataResol_z*10.+136*20.]) / 10.
#     subject_anchor2_wrt_wholebrainWithMargin_atlasResol = np.array([461*20., 151*20., wholebrainWithMargin_origin_wrt_wholebrain_dataResol_z*10.+136*20.]) / 10.
# elif stack == 'MD595':
#     subject_anchor1_wrt_wholebrainWithMargin_atlasResol = np.array([674*20., 225*20., wholebrainWithMargin_origin_wrt_wholebrain_dataResol_z*10.+137*20.]) / 10.
#     subject_anchor2_wrt_wholebrainWithMargin_atlasResol = np.array([486*20., 180*20., wholebrainWithMargin_origin_wrt_wholebrain_dataResol_z*10.+137*20.]) / 10.
# elif stack == 'MD598':
#     subject_anchor1_wrt_wholebrainWithMargin_atlasResol = np.array([628*20., 206*20., wholebrainWithMargin_origin_wrt_wholebrain_dataResol_z*10.+165*20.]) / 10.
#     subject_anchor2_wrt_wholebrainWithMargin_atlasResol = np.array([464*20., 164*20., wholebrainWithMargin_origin_wrt_wholebrain_dataResol_z*10.+165*20.]) / 10.
# elif stack == 'MD599':
#     subject_anchor1_wrt_wholebrainWithMargin_atlasResol = np.array([682*20., 222*20., wholebrainWithMargin_origin_wrt_wholebrain_dataResol_z*10.+129*20.]) / 10.
#     subject_anchor2_wrt_wholebrainWithMargin_atlasResol = np.array([505*20., 175*20., wholebrainWithMargin_origin_wrt_wholebrain_dataResol_z*10.+129*20.]) / 10.
# elif stack == 'MD602':
#     subject_anchor1_wrt_wholebrainWithMargin_atlasResol = np.array([668*20., 197*20., wholebrainWithMargin_origin_wrt_wholebrain_dataResol_z*10.+135*20.]) / 10.
#     subject_anchor2_wrt_wholebrainWithMargin_atlasResol = np.array([460*20., 157*20., wholebrainWithMargin_origin_wrt_wholebrain_dataResol_z*10.+135*20.]) / 10.
# elif stack == 'MD603':
#     subject_anchor1_wrt_wholebrainWithMargin_atlasResol = np.array([651*20., 229*20., wholebrainWithMargin_origin_wrt_wholebrain_dataResol_z*10.+153*20.]) / 10.
#     subject_anchor2_wrt_wholebrainWithMargin_atlasResol = np.array([446*20., 168*20., wholebrainWithMargin_origin_wrt_wholebrain_dataResol_z*10.+153*20.]) / 10.
# elif stack == 'MD661':
#     subject_anchor1_wrt_wholebrainWithMargin_atlasResol = np.array([559*20., 209*20., wholebrainWithMargin_origin_wrt_wholebrain_dataResol_z*10.+140*20.]) / 10.
#     subject_anchor2_wrt_wholebrainWithMargin_atlasResol = np.array([383*20., 166*20., wholebrainWithMargin_origin_wrt_wholebrain_dataResol_z*10.+140*20.]) / 10.
# elif stack == 'DEMO998':
#     mid_z_wrt_wholebrainWithMargin = 0 # this must be changed
#     subject_anchor1_wrt_wholebrain_atlasResol = np.array([wholebrainWithMargin_origin_wrt_wholebrain_dataResol_x * 10. + 558*20., 
#                                                           wholebrainWithMargin_origin_wrt_wholebrain_dataResol_y * 10. + 207*20., 
#                                                           wholebrainWithMargin_origin_wrt_wholebrain_dataResol_z*10. + mid_z_wrt_wholebrainWithMargin*20.]) / 10.
#     subject_anchor2_wrt_wholebrain_atlasResol = np.array([wholebrainWithMargin_origin_wrt_wholebrain_dataResol_x * 10. + 366*20., 
#                                                           wholebrainWithMargin_origin_wrt_wholebrain_dataResol_y * 10. + 171*20., 
#                                                           wholebrainWithMargin_origin_wrt_wholebrain_dataResol_z*10. + mid_z_wrt_wholebrainWithMargin*20.]) / 10.
# else:
#     raise

In [9]:
def align_anchors(pm1, pm2, pf1, pf2):
    """
    Align the vector (pm1, pm2) and vector (pf1, pf2), and align the two middle points. 
    """
    
    t = ((pf1 + pf2) / 2. - (pm1 + pm2) / 2.)
    
    subject_d = pf1 - pf2
    atlas_d = pm1 - pm2

    subject_d_n = subject_d / np.linalg.norm(subject_d)
    atlas_d_n = atlas_d / np.linalg.norm(atlas_d)

    R = R_align_two_vectors(atlas_d_n, subject_d_n)
    
    T = np.zeros((3,4))
    T[:3, :3] = R
#     T[:3, 3] = np.dot(R, t)
    T[:3, 3] = t
    
    return T

In [10]:
wholebrainWithMargin_origin_wrt_wholebrain_dataResol = \
np.r_[wholebrainWithMargin_origin_wrt_wholebrain_dataResol_x,
      wholebrainWithMargin_origin_wrt_wholebrain_dataResol_y,
      wholebrainWithMargin_origin_wrt_wholebrain_dataResol_z]

In [11]:
# if stack == 'DEMO998':
#     wholebrainWithMargin_origin_wrt_wholebrain_dataResol = \
#     np.r_[wholebrainWithMargin_origin_wrt_wholebrain_dataResol_x,
#           wholebrainWithMargin_origin_wrt_wholebrain_dataResol_y,
#           wholebrainWithMargin_origin_wrt_wholebrain_dataResol_z]
# else:
#     wholebrainWithMargin_origin_wrt_wholebrain_dataResol = \
# np.r_[wholebrainWithMargin_origin_wrt_wholebrain_dataResol_x,
#       wholebrainWithMargin_origin_wrt_wholebrain_dataResol_y,
#       0]

#     subject_anchor1_wrt_wholebrain_atlasResol = subject_anchor1_wrt_wholebrainWithMargin_atlasResol + \
#     wholebrainWithMargin_origin_wrt_wholebrain_dataResol # only valid because dataResol is same as atlasResol

#     subject_anchor2_wrt_wholebrain_atlasResol = subject_anchor2_wrt_wholebrainWithMargin_atlasResol + \
#     wholebrainWithMargin_origin_wrt_wholebrain_dataResol # only valid because dataResol is same as atlasResol

In [12]:
atlas_anchor1_wrt_canonicalAtlasSpace_atlasResol

array([200.54678679,  68.66154597,   0.        ])

In [13]:
subject_anchor1_wrt_wholebrain_atlasResol

array([1373.,  556.,  402.])

In [14]:
T_atlas_wrt_canonicalAtlasSpace_subject_wrt_wholebrain_atlasResol = \
align_anchors(atlas_anchor1_wrt_canonicalAtlasSpace_atlasResol, atlas_anchor2_wrt_canonicalAtlasSpace_atlasResol,
             subject_anchor1_wrt_wholebrain_atlasResol, subject_anchor2_wrt_wholebrain_atlasResol)

In [15]:
print T_atlas_wrt_canonicalAtlasSpace_subject_wrt_wholebrain_atlasResol

[[ 9.94682907e-01  1.02994988e-01  0.00000000e+00  1.17774282e+03]
 [-1.02994988e-01  9.94682907e-01  0.00000000e+00  5.10443355e+02]
 [ 0.00000000e+00  0.00000000e+00  1.00000000e+00  4.02000000e+02]]


In [23]:
# https://www.lfd.uci.edu/~gohlke/code/transformations.py.html

def quaternion_about_axis(angle, axis):
    """Return quaternion for rotation about axis.

    >>> q = quaternion_about_axis(0.123, [1, 0, 0])
    >>> numpy.allclose(q, [0.99810947, 0.06146124, 0, 0])
    True

    """
    q = np.array([0.0, axis[0], axis[1], axis[2]])
    qlen = np.linalg.norm(q)
    q *= np.sin(angle/2.0) / qlen
    q[0] = np.cos(angle/2.0)
    return q


def quaternion_matrix(quaternion):
    """Return homogeneous rotation matrix from quaternion.

    >>> M = quaternion_matrix([0.99810947, 0.06146124, 0, 0])
    >>> numpy.allclose(M, rotation_matrix(0.123, [1, 0, 0]))
    True
    >>> M = quaternion_matrix([1, 0, 0, 0])
    >>> numpy.allclose(M, numpy.identity(4))
    True
    >>> M = quaternion_matrix([0, 1, 0, 0])
    >>> numpy.allclose(M, numpy.diag([1, -1, -1, 1]))
    True

    """
    q = np.array(quaternion, dtype=np.float64, copy=True)
    n = np.dot(q, q)
    q *= np.sqrt(2.0 / n)
    q = np.outer(q, q)
    return np.array([
        [1.0-q[2, 2]-q[3, 3],     q[1, 2]-q[3, 0],     q[1, 3]+q[2, 0], 0.0],
        [    q[1, 2]+q[3, 0], 1.0-q[1, 1]-q[3, 3],     q[2, 3]-q[1, 0], 0.0],
        [    q[1, 3]-q[2, 0],     q[2, 3]+q[1, 0], 1.0-q[1, 1]-q[2, 2], 0.0],
        [                0.0,                 0.0,                 0.0, 1.0]])

rand_vec = np.random.uniform(size=3)
rand_vec = rand_vec / np.linalg.norm(rand_vec)
rand_rot_amount = np.random.uniform(high=np.deg2rad(5))
perturb_rot = quaternion_matrix(quaternion_about_axis(rand_rot_amount, rand_vec))

perturb_xyz = np.random.choice(np.arange(-30, 30), 3)

T_atlas_wrt_canonicalAtlasSpace_subject_wrt_wholebrain_atlasResol = \
np.dot(T_atlas_wrt_canonicalAtlasSpace_subject_wrt_wholebrain_atlasResol, perturb_rot)
T_atlas_wrt_canonicalAtlasSpace_subject_wrt_wholebrain_atlasResol[:3, 3] += perturb_xyz

In [24]:
print T_atlas_wrt_canonicalAtlasSpace_subject_wrt_wholebrain_atlasResol

[[ 9.96794573e-01  7.88366266e-02  1.36901111e-02  1.15974282e+03]
 [-7.83927867e-02  9.96460235e-01 -3.03912136e-02  5.13443355e+02]
 [-1.60375592e-02  2.92205308e-02  9.99444324e-01  4.25000000e+02]]


In [26]:
fp = os.path.join(DATA_ROOTDIR, 'CSHL_simple_global_registration', stack + '_T_atlas_wrt_canonicalAtlasSpace_subject_wrt_wholebrain_atlasResol.txt')
create_parent_dir_if_not_exists(fp)
np.savetxt(fp, T_atlas_wrt_canonicalAtlasSpace_subject_wrt_wholebrain_atlasResol)

In [56]:
# bp.pack_ndarray_file(T_atlas_wrt_canonicalAtlasSpace_subject_wrt_wholebrain_atlasResol, 
#                      os.path.join(DATA_ROOTDIR, 'CSHL_simple_global_registration', stack + '_T_atlas_wrt_canonicalAtlasSpace_subject_wrt_wholebrain_atlasResol.bp'))